# Generated by Django 5.0.6 on 2024-05-31 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fresh_news', '0002_alter_news_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='publish_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
