# Generated by Django 5.0.6 on 2024-05-31 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fresh_news', '0003_alter_news_publish_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='from_source',
            field=models.URLField(blank=True, null=True),
        ),
    ]
