# Generated by Django 5.0.6 on 2024-06-28 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fresh_news", "0005_news_image_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="title",
            field=models.CharField(max_length=1100),
        ),
    ]
