# Generated by Django 5.0.6 on 2024-06-28 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fresh_news", "0006_alter_news_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="title",
            field=models.TextField(),
        ),
    ]
